name = "SingleCellSizeData"
uuid = "a1b2c3d4-e5f6-7890-1234-567890abcdef"
authors = ["Your Name <your.email@example.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10"
DataFrames = "1"
Distributions = "0.25"
Optim = "1.13.3"
Plots = "1"
StatsBase = "0.33"
StatsPlots = "0.15"
Turing = "0.42.4"
XLSX = "0.10.4"
julia = "1.6"
