name = "SingleCellSizeData"
uuid = "a1b2c3d4-e5f6-7890-1234-567890abcdef"
authors = ["Your Name <your.email@example.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.6"
DataFrames = "1"
CSV = "0.10"
StatsBase = "0.33"
Plots = "1"
StatsPlots = "0.15"
Distributions = "0.25"